---
- name: Manage Debian 822 Repository
  when: step['repo_type'] | lower == 'deb822'
  ansible.builtin.deb822_repository:
    name: "{{ step['name'] }}"
    state: "{{ step['state'] | default(omit) }}"
    # Module-specific Parameters
    allow_downgrade_to_insecure: "{{ step['allow_downgrade_to_insecure'] | default(omit) }}"
    allow_insecure: "{{ step['allow_insecure'] | default(omit) }}"
    allow_weak: "{{ step['allow_weak'] | default(omit) }}"
    architectures: "{{ step['architectures'] | default(omit) }}"
    by_hash: "{{ step['by_hash'] | default(omit) }}"
    check_date: "{{ step['check_date'] | default(omit) }}"
    check_valid_until: "{{ step['check_valid_until'] | default(omit) }}"
    components: "{{ step['components'] | default(omit) }}"
    date_max_future: "{{ step['date_max_future'] | default(omit) }}"
    enabled: "{{ step['enabled'] | default(omit) }}"
    inrelease_path: "{{ step['inrelease_path'] | default(omit) }}"
    languages: "{{ step['languages'] | default(omit) }}"
    mode: "{{ step['mode'] | default(omit) }}"
    pdiffs: "{{ step['pdiffs'] | default(omit) }}"
    signed_by: "{{ step['signed_by'] | default(omit) }}"
    suites: "{{ step['suites'] | default(omit) }}"
    targets: "{{ step['targets'] | default(omit) }}"
    trusted: "{{ step['trusted'] | default(omit) }}"
    types: "{{ step['types'] | default(omit) }}"
    uris: "{{ step['uris'] | default(omit) }}"
