# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC-PDM-1.0
objects: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.4.3
