# SPDX-FileCopyrightText: 2025 Industrial Info Resources, Inc.
# SPDX-FileContributor: William P. Marshall
#
# SPDX-License-Identifier: GPL-3.0-or-later

objects:
  role:
    acme_sh:
      description: Manage acme.sh, a lightweight certificate managemenent tool.
      name: acme_sh
      version_added: 1.4.0
    deps_mgr:
      description: Manages OS packages and repositories
      name: deps_mgr
      version_added: 1.0.0
    dirtree:
      description: 'Creates a directory tree from a dictionary of dictionaries. Lets
        you declare such a tree in an intuitive hierarchical manner instead of a flat
        list of paths.'
      name: dirtree
      version_added: 1.0.0
    java:
      description: Install Java from a variety of vendors and variants.
      name: java
      version_added: 1.3.0
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter:
    from_toml:
      description: Converts a dictionary into a nice TOML-formatted string
      name: from_toml
      version_added: 1.5.0
    generate_paths:
      description: Flattens a nested directory tree of directory names into a list
        of paths.
      name: generate_paths
      version_added: 1.0.0
    get_grpname:
      description: Match the input name or GID to a real group and return its name.
      name: get_grpname
      version_added: 1.0.0
    to_nice_toml:
      description: Converts a dictionary into a nice TOML-formatted string
      name: to_nice_toml
      version_added: 1.5.0
    to_toml:
      description: Converts a dictionary into a nice TOML-formatted string
      name: to_toml
      version_added: 1.5.0
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.5.0
