---
ancestor: null
releases:
  1.0.0:
    release_date: '2024-10-22'
  1.0.1:
    changes:
      bugfixes:
        - 'Plugins - All output strings are now run through the included to_text function
          to ensure proper encoding.

          See: https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#string-encoding'
      doc_changes:
        - LICENSE - corrected licensing to match reality.
        - Plugins - Added documentation to all plugins.
        - READMEs - Added parameter definitions, expanded on dependency usage, and
          eliminated leftover templating cruft.
      release_summary: Update documentation collection-wide and make minor bugfixes
        to plugins.
    fragments:
      - 2-correct-documentation.yml
    release_date: '2024-10-24'
  1.0.2:
    changes:
      bugfixes:
        - deps_mgr - Quoted and bracketed the "state" variable.  This prevents unexpected
          failures due to custom states.
      release_summary: Fix package installation issues with custom state values.
    fragments:
      - 3-quote-state-variable.yml
    release_date: '2024-10-24'
  1.0.3:
    changes:
      bugfixes:
        - deps_mgr - Quoted the name of the 'Make Packages' task in packages.yml so
          the state variable value is included.
      minor_changes:
        - deps_mgr - You can now specify whether to use the `lowest_only` or `precision`
          merge methods for packages and repositories.
      release_summary: Allow the user to specify how different levels of the deps_mgr_list
        are merged.
    fragments:
      - 4-quote-make-packages-name.yml
      - 6-merge-method.yml
    release_date: '2024-10-28'
  1.1.0:
    changes:
      doc_changes:
        - deps_mgr - Added a breakdown of `dep_mgr_list` syntax.
        - deps_mgr - Added a list of common repository parameters.
        - deps_mgr - Added documentation for the new repository types.
      minor_changes:
        - collection - new requirement that community.general be version 8.2.0 or
          later to support community.general.dnf_conf_manager.
        - deps_mgr - added support for apt, apt-repo, copr, and sorcery repositories/grimoires.
        - deps_mgr - split repository module code into separate files for each type.  Moved
          repo var generation to the repositories.yml file.
      release_summary: Expanded the number of supported package managers and organized
        steps for using each one into its own file.
    fragments:
      - 10-refactor-and-improve-deps_mgr.yml
    release_date: '2024-11-06'
  1.2.0:
    changes:
      bugfixes:
        - deps_mgr - all repository management types now require `name` and ensure
          it is mapped to a parameter. i.e., the previously documented behavior is
          now enforced.
      minor_changes:
        - deps_mgr - added the new variable `deps_mgr_package_default_state`, which
          allows users to set the default state for simple packages.
      release_summary: deps_mgr - Reduced duplicative labels, fixed issues with repository
        name, added an option to change the default package state, and added integration
        tests.
    fragments:
      - 11-improve-labeling.yml
    release_date: '2024-12-04'
  1.3.0:
    changes:
      doc_changes:
        - deps_mgr - updated the README.md to fix spelling and formatting errors.
      minor_changes:
        - deps_mgr - alpine repositories now support copying the public key from the
          controller instead of downloading from a URL.
        - 'deps_mgr - will now gather required facts if they are missing. This allows
          the role to work if the playbook has``gather_facts: false`` or an incompatible
          ``gather_subset`` setting.'
      release_summary: Added a new Java role and made minor enhancements to deps_mgr.
    fragments:
      - 12-add-java-role.yml
    release_date: '2025-02-11'
  1.3.1:
    changes:
      bugfixes:
        - Missing destination directory creation step in archive extraction.
        - The `java_archive_path` variable was composed using the invalid `java_archive_installers`
          variable instead of the `java_archives` variable.
        - Typo, `ansible.builtin.splitent` was used instead of `ansible.builtin.splitext`.
        - Unarchive task required remote_src = true to work.
      minor_changes:
        - can now skip changing alternatives after installing an archived copy of
          Java.
      release_summary: fixed a bug that broke archive-based installs of java.
    fragments:
      - 13-fix-broken-java-archive-installers.yml
    release_date: '2025-03-18'
  1.3.2:
    changes:
      doc_changes:
        - docs(deps_mgr) - clarify examples and how the alpine repo_type is managed.
        - docs(java) - fix typo in vars/main.yml comments.
        - docs(java) - remove duplicate text from parameter description.
      release_summary: Fixes documentation by removing duplicates, clarifying examples,
        and rectifying typos.
    fragments:
      - 14-docs-fixup.yml
    release_date: '2025-04-16'
  1.3.3:
    changes:
      bugfixes:
        - deps_mgr - flatten the query results used to loop Manage Packages by Desired
          State in packages.yml.  This will allow us to use query to ensure looping,
          but flatten the looped value down to one list.
        - deps_mgr - repository_types handlers now use `default(omit)` when a parameter
          is not specified.  Fixes issues related to type casting.
      release_summary: In deps_mgr, fix looping issues with the packages handler and
        default value issues with the repository_types handlers.
    fragments:
      - 15-fix-repo-defaults.yaml
    release_date: '2025-04-17'
  1.4.0:
    changes:
      release_summary: Add a role to manage acme.sh and fix a few documentation issues.
    fragments:
      - 16-add-acme_sh-role.yml
    objects:
      role:
        - description: 'A role to install/update/remove, configure, and schedule acme.sh.
            acme.sh is a certificate manager written purely in Shell and thus has
            minimal dependencies (wget or curl). It is highly extensible and works
            on just about anything.

            '
          name: acme_sh
          namespace: null
    release_date: '2025-08-13'
  1.4.1:
    changes:
      bugfixes:
        - '`acme_sh` role would fail when you used cron as the scheduler. This was
          caused by a lack of error handling for systemd_service ansible roles, which
          produced errors about systemd services not existing.

          '
      release_summary: Fixes a bug in the acme_sh role that causes it to fail when
        specifying cron as the scheduler.
    fragments:
      - 17-fix-acmesh-systemd-svc
    release_date: '2025-08-13'
