---
- name: Remove ACME.sh
  tags: ['acmesh::install']
  ansible.builtin.command:
    cmd: "{{ (acmesh_home, 'acme.sh') | ansible.builtin.path_join }} --uninstall --no-cron --home \"{{ acmesh_home }}\""
    removes: "{{ (acmesh_home, 'acme.sh') | ansible.builtin.path_join }}"

- name: Delete directory
  tags: ['acmesh::install']
  ansible.builtin.file:
    path: "{{ acmesh_home }}"
    state: absent

- name: Delete acme.sh Local Facts
  tags: ['acmesh::install']
  ansible.builtin.file:
    path: "{{ ('/etc', 'ansible', 'facts.d', 'acme.sh.fact') | ansible.builtin.path_join }}"
    state: absent
